# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 343a18c2e4de3bd764458ff27727ee8603d36ec9b15a1a0bcf8eba55e1465eb893729921b57a0359ec431e84de72247180af2220ce81448d750fb0a9f99d7ebf

test:
  secret_key_base: 5bb34150acbecadf2da5ae5b07d6eacedd82331805d454bb92207cc1cf8d35ad6f7edd2086f9e4ace5dc1c08a66e6798530cba182a1fe66b3145bab520b079f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
